#! /bin/sh

######### Autostart
bash "$HOME/.config/bspwm/plank.sh" &
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
plank &
ibus-daemon -drx &
xsetroot -cursor_name left_ptr &tray
feh --bg-fill /home/trcminh/Pictures/bg6.jpg &
$HOME/.config/polybar/launch.sh &
eww daemon &
dunst &
mpd &
mpDris2 &
#$HOME/.config/bspwm/scripts/eww_fullscreen_fix.sh &

bspc monitor -d I II III IV V 
VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           8
bspc config split_ratio          0.6
bspc config normal_border_color "#0d1117"
bspc config focused_border_color "#0d1117"
bspc config presel_feedback_color "#0d1117"
bspc config focus_follows_pointer true

bspc config ignore_ewmh_struts true
bspc config top_padding 20

bspc rule -a mpv state=floating
bspc rule -a Plank manage=off border=off locked=on focus=off follow=off layer=above

